[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
extend-select = ["I"]
ignore = ["E501", "F401"]

[tool.pyright]
typeCheckingMode = "strict"
reportMissingImports = true
reportUnusedVariable = "warning"
reportUnusedFunction = "warning"